version: 2.1

executors:
  maven-executor:
    docker:
      # Use an official Maven Docker image that comes with Maven and JDK pre-installed
      - image: circleci/openjdk:17-jdk
    working_directory: ~/repo

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout  # Check out the source code

      # Cache dependencies to speed up subsequent builds
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      # Run Maven commands to build and test the project
      - run:
          name: Build and Test with Maven
          command: mvn clean install

      # Save Maven dependencies to the cache for future jobs
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

      # Store test results for analysis in CircleCI UI
      - store_test_results:
          path: target/surefire-reports

      # Store the generated JAR file as an artifact
      - store_artifacts:
          path: target/*.jar
          destination: build-artifacts

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
