version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:17.0 
    working_directory: ~/repo

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout  # Checkout the source code

      # Set up JFrog CLI
      

      # Build the project using Maven
      - run:
          name: Build with Maven
          command: mvn -B package --file spring-boot-ems/pom.xml

   

      # Slack Notification (Using curl to send notification)
     

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
