name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file spring-boot-ems/pom.xml
      
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2
      with:
          projectBaseDir: ./spring-boot-ems
          args: >
           -Dsonar.organization=ajayingale12345
           -Dsonar.projectKey=ajayingale12345_GithubAction_POC_CI
           -Dsonar.sources=src/main
           -Dsonar.java.binaries=target

    
